### ISSUE TITLE
Maybe add the `runtime-compose-ui` dependency automatically if `buildFeatures.compose` is true?

### ISSUE THREAD

**Issue by efemoney** [cashapp/paraphrase#189]

**Comment by JakeWharton** [comment]
Seems reasonable

**Comment by theisenp** [comment]
Good idea! Initially I was worried that this would force presenter modules using both Paraphrase and [Molecule](https://github.com/cashapp/Molecule) to also depend on the `runtime-compose-ui`, but actually it seems like Molecule doesn't require the Compose build feature.
